# Store the locators for the stage environment here. 
# This file is used by the LocatorRepository class to fetch the locators based on the current environment.

# Examples:
# login.username=id:user-name
# inventory.cart=class:shopping_cart_link
# item_detail.name=css:.inventory_details_name