login.username=id:user-name
login.password=id:password
login.button=id:login-button
login.error_message=css:.error-message-container

inventory.title=class:title
inventory.burger_menu=id:react-burger-menu-btn
inventory.shopping_cart=class:shopping_cart_link
inventory.sort_dropdown=class:product_sort_container
inventory.all_items=css:.inventory_item
inventory.all_item_names=css:.inventory_item_name
inventory.all_item_description=css:.inventory_item_desc
inventory.all_item_price=css:.inventory_item_price
inventory.all_item_image=css:.inventory_item_img img
inventory.all_add_to_cart_buttons=css:.btn_inventory
inventory.all_remove_to_cart_buttons=css:.btn_inventory
inventory.cart_badge=class:shopping_cart_badge

item_detail.name=css:.inventory_details_name
item_detail.description=css:.inventory_details_desc
item_detail.price=css:.inventory_details_price
item_detail.image=css:.inventory_details_img
item_detail.back=css:.inventory_details_back_button
item_detail.add_to_cart=css:.btn_inventory
item_detail.remove=css:.btn_inventory
item_detail.cart_badge=class:shopping_cart_badge